src/KanbanApp/Models/Board.cs
namespace KanbanApp.Models
{
    public class Board
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public int CreatorID { get; set; }
        public User CreatorUser { get; set; }

        public List<Column> Columns { get; set; }
        public List<UserBoard> UserBoards { get; set; }
        public static string StringCut(string str)
        {
            if (str.Length > 20)
            {
                str = str.Substring(0, 19) + "...";
            }
            return str;
        }
    }
}

src/KanbanApp/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KanbanApp.Data;
using KanbanApp.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Column = KanbanApp.Models.Column;
using NuGet.Packaging;

namespace KanbanApp.Controllers
{
    public class BoardsController : Controller
    {
        private readonly KanbanAppContext _context;

        public BoardsController(KanbanAppContext context)
        {
            _context = context;
        }

        private bool BoardExists(int id)
        {
            return _context.Board.Any(e => e.ID == id);
        }

        [HttpGet("Boards/Board/{boardID}")]
        public async Task<IActionResult> Board(int boardID)
        {
            if (_context.Board.FirstOrDefault(x => x.ID == boardID) == null || 
                HttpContext.Session.GetInt32("UserID") == null || 
                _context.UserBoard.FirstOrDefault(x => x.UserID == HttpContext.Session.GetInt32("UserID")) == null)
            {
                return NotFound();
            }
            List<Column> columns = _context.Column.Where(x => x.BoardID == boardID).Include(x => x.IssueColumns.Where(y => !y.IsDeleted)).ToList();
            ViewBag.BoardName = _context.Board.FirstOrDefault(x => x.ID == boardID).Name;
            ViewBag.BoardID = _context.Board.FirstOrDefault(x => x.ID == boardID).ID;

            columns.ForEach(x => x.IssueColumns.ForEach(y => y.Issue = _context.Issue.Include(w => w.Performer).Include(w => w.Creator).FirstOrDefault(z => z.ID == y.IssueID)));

            var reponsibilities = _context.UserBoard.Where(x => x.BoardID == boardID)
                .Select(c => new SelectListItem
                {
                    Value = c.UserID.ToString(),
                    Text = c.User.Email
                }).ToList();

            ViewBag.Responsibilities = reponsibilities;
            if (_context.UserBoard.FirstOrDefault(x => x.UserID == HttpContext.Session.GetInt32("UserID") && x.BoardID == boardID).UserRole == UserRoles.Admin)
            {
                ViewBag.UserAdmin = true;
            }
            else
            {
                ViewBag.UserAdmin = false;
            }

            List<Issue> issues = new List<Issue>();

            foreach(var column in columns)
            {
                issues.AddRange(column.IssueColumns.Select(x => x.Issue));
            }
            ViewBag.BoardTasks = issues;

            return View(columns);
        }

        [HttpPost]
        public IActionResult CreateTask([Bind("ID, Name, Description, DeadlineDate, Status, Priority, PerformerID")] Issue issue, IFormCollection formData)
        {
            int? userSessionID = HttpContext.Session.GetInt32("UserID");

            User creator = _context.User.FirstOrDefault(x => x.ID == userSessionID);

            Issue newIssue = new Issue();
            newIssue.Name = issue.Name;
            newIssue.Description = issue.Description ?? "";
            if(issue.DeadlineDate.Date < DateTime.Now.Date)
                newIssue.DeadlineDate = DateTime.Now.Date;
            else
                newIssue.DeadlineDate = issue.DeadlineDate.Date;
            newIssue.Status = issue.Status;
            newIssue.Priority = issue.Priority;
            newIssue.PerformerID = issue.PerformerID;
            newIssue.CreatorID = (int)userSessionID;
            _context.Add(newIssue);
            _context.SaveChanges();

            IssueColumn issueColumn = new IssueColumn();
            issueColumn.IssueID = newIssue.ID;
            issueColumn.ColumnID = _context.Column.FirstOrDefault(x => x.BoardID == int.Parse(formData["boardID"]) && x.Name == @Issue.StatusToString(newIssue.Status)).ID;
            issueColumn.DeleteDate = DateTime.Now;
            issueColumn.IsDeleted = false;
            _context.Add(issueColumn);
            _context.SaveChanges();

            return RedirectToAction("Board", new { boardID = int.Parse(formData["boardID"]) });

        }

        [HttpGet("Boards/JoinBoard/{boardID}")]
        public async Task<IActionResult> JoinBoard(int boardID)
        {
            User currUser = _context.User.FirstOrDefault(x => x.ID == HttpContext.Session.GetInt32("UserID"));
            if (currUser != null)
            {
                UserBoard userBoard = new UserBoard();
                userBoard.BoardID = boardID;
                userBoard.UserID = currUser.ID;
                userBoard.UserRole = UserRoles.Editor;
                _context.Add(userBoard);
                _context.SaveChanges();
                return RedirectToAction("Board", new { boardID = boardID });
            }
            else if (_context.UserBoard.FirstOrDefault(x=> x.UserID == currUser.ID && x.BoardID==boardID) != null)
            {
                return RedirectToAction("Board", new { boardID = boardID });
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<IActionResult> DeleteBoard(IFormCollection formData)
        {
            var board = await _context.Board.FindAsync(int.Parse(formData["boardID"]));
            if (board != null)
            {
                _context.Board.Remove(board);
            }

            await _context.SaveChangesAsync();
            return Redirect("/");
        }
        [HttpPost]
        public async Task<IActionResult> EditBoard([Bind("ID,Name")] Board board, IFormCollection formData)
        {
            var currBoard = await _context.Board.FindAsync(int.Parse(formData["boardID"]));
            currBoard.Name = board.Name;

            await _context.SaveChangesAsync();
            return RedirectToAction("Board", new { boardID = int.Parse(formData["boardID"]) });
        }

       
        [HttpPost]
        public async Task<IActionResult> EditTask([Bind("ID, Name, Description, DeadlineDate, Status, Priority, PerformerID")] Issue issue, IFormCollection formData, int taskID)
        {
            Issue currIssue = await _context.Issue.FindAsync(int.Parse(formData["taskID"]));
            currIssue.Name = issue.Name;
            currIssue.Description = issue.Description ?? "";
            if (issue.DeadlineDate.Date >= DateTime.Now.Date || issue.DeadlineDate.Date > currIssue.DeadlineDate.Date)
                currIssue.DeadlineDate = issue.DeadlineDate;
            currIssue.Status = issue.Status;
            if (issue.Status == IssueStatus.Completed)
            {
                currIssue.EndDate = DateTime.Now.Date;
            }
            currIssue.Priority = issue.Priority;
            currIssue.PerformerID = issue.PerformerID;
            _context.SaveChanges();
            await _context.SaveChangesAsync();
            IssueColumn issueColumn = _context.IssueColumn.FirstOrDefault(x => x.IssueID == currIssue.ID);
            issueColumn.ColumnID = _context.Column.FirstOrDefault(x => x.BoardID == int.Parse(formData["boardID"]) && x.Name == @Issue.StatusToString(currIssue.Status)).ID;

            await _context.SaveChangesAsync();
            return RedirectToAction("Board", new { boardID = int.Parse(formData["boardID"]) });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(IFormCollection formData, int userID)
        {
            int boardID = int.Parse(formData["boardID"]);
            UserBoard userBoard = await _context.UserBoard.FirstOrDefaultAsync(x => x.UserID == userID && x.BoardID == boardID);

            if (userBoard != null)
            {
                _context.Remove(userBoard);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("UserList", "Users", new { boardID });
        }


        [HttpPost]
        public async Task<IActionResult> DeleteTask(IFormCollection formData)
        {
            var taskCol = _context.IssueColumn.FirstOrDefault(x => x.IssueID == int.Parse(formData["taskID"]));
            if (taskCol != null)
            {
                taskCol.IsDeleted = true;
                taskCol.DeleteDate = DateTime.Now.Date; 
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Board", new { boardID = int.Parse(formData["boardID"]) });
        }

        [HttpGet("/Boards/ArchiveOfTasks/{boardID}")]
        public async Task<IActionResult> ArchiveOfTasks(int boardID)
        {
            int? userSessionID = HttpContext.Session.GetInt32("UserID");
            User currentUser = await _context.User.FindAsync(userSessionID);
            var userOnBoard = _context.UserBoard.FirstOrDefault(x => x.UserID == currentUser.ID);
            if (currentUser == null || userOnBoard == null || userOnBoard.UserRole != UserRoles.Admin)
            {
                return NotFound();
            }
            ViewBag.BoardName = _context.Board.FirstOrDefault(x => x.ID == boardID).Name;
            ViewBag.BoardID = _context.Board.FirstOrDefault(x => x.ID == boardID).ID;
            List<Column> columns = _context.Column.Where(x => x.BoardID == boardID).Include(x => x.IssueColumns.Where(y => y.IsDeleted)).ToList();
            columns.ForEach(x => x.IssueColumns.ForEach(y => y.Issue = _context.Issue.Include(w => w.Performer).Include(w => w.Creator).FirstOrDefault(z => z.ID == y.IssueID)));

            return View(columns);
        }
        [HttpGet("/Boards/RestoreTask/{taskID}")]
        public async Task<IActionResult> RestoreTask(int taskID, int boardID)
        {
            var taskCol = _context.IssueColumn.FirstOrDefault(x => x.IssueID == taskID);
            if (taskCol != null)
            {
                taskCol.IsDeleted = false;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("ArchiveOfTasks", new {boardID = boardID});
        }
    }

}

src/KanbanApp/Views/Boards/ArchiveOfTasks.cshtml
@using KanbanApp.Controllers
@using KanbanApp.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Column>

@{
    Layout = "_Layout";
}
<header>
    <h1>@Board.StringCut(@ViewBag.BoardName)</h1>
    <h3>Архив удаленных задач</h3>
    <a href="/Users/UserProfile" class="profile-icon">
        <i class="la la-user-circle"></i>
    </a>
</header>

<div class="archived-tasks">
    <table>
        <thead>
            <tr>
                <th>Удалена</th>
                <th>Название</th>
                <th>Описание</th>
                <th>Приоритет</th>
                <th>Статус</th>
                <th>Создатель</th>
                <th>Ответственный</th>
                <th>Срок</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Column col in Model)
            {
                @foreach (IssueColumn ic in col.IssueColumns)
                {
                    <tr>
                        <td>@ic.DeleteDate.ToString("d")</td>
                        <td>@ic.Issue.Name</td>
                        <td>@ic.Issue.Description</td>
                        <td>@Issue.PriorityToString(ic.Issue.Priority)</td>
                        <td>@Issue.StatusToString(ic.Issue.Status)</td>
                        <td>@Issue.StringCut(ic.Issue.Creator.Email)</td>
                        <td>@Issue.StringCut(ic.Issue.Performer.Email)</td>
                        <td>@ic.Issue.DeadlineDate.ToString("d")</td>
                        <td>
                            <a href="/Boards/RestoreTask/@ic.IssueID?boardID=@ViewBag.BoardID" class="restore-button">Восстановить</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

src/KanbanApp/Views/Boards/Board.cshtml
@using KanbanApp.Controllers
@using KanbanApp.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Column>

@{
    Layout = "_Layout";
}
<header>
    @if (ViewBag.UserAdmin)
    {
        <a href="#edit-board" rel="modal:open" class="board-name">
            <h1>@Board.StringCut(@ViewBag.BoardName)</h1>
        </a>
    }
    else {
        <h1>@ViewBag.BoardName</h1>
    }
    <div class="add-buttons">
        @if (ViewBag.UserAdmin)
        {   <a href="/Users/UserList/@ViewBag.BoardID">Список участников</a>
            <a href="#generate-link" rel="modal:open">Сгенерировать приглашение</a>
            <a href="#delete-board" rel="modal:open" class="delete">Удалить доску</a>
            <a href="/Boards/ArchiveOfTasks/@ViewBag.BoardID">Архив удаленных задач</a>
        }
    </div>
    <a href="/Users/UserProfile" class="profile-icon">
        <i class="la la-user-circle"></i>
    </a>
</header>

<div class="add-buttons">
    @if (Model.Count > 0)
    {
        <a href="#add-task" rel="modal:open">Добавить Задачу</a>
    }
    <form asp-action="CreateColumn" asp-controller="Boards" method="post">
        <input type="hidden" value="@ViewBag.BoardID" name="boardID" />
    </form>
    
</div>

<div class="board">
    <div class="boardWrapper">
        @foreach (Column col in Model)
        {
            <div class="column">
                <div class="column-title">@col.Name</div>
                @foreach (IssueColumn ic in col.IssueColumns)
                {
                    string taskClass = "";

                    switch (ic.Issue.Priority)
                    {
                        case Priority.Low:
                            taskClass = "task low-priority";
                            break;
                        case Priority.Middle:
                            taskClass = "task middle-priority";
                            break;
                        case Priority.High:
                            taskClass = "task high-priority";
                            break;
                        default:
                            taskClass = "task";
                            break;
                    }

                    <a class="edit-task-link" href="#edit-task" rel="modal:open" data-task-id="@ic.Issue.ID">
                        <div class="@taskClass">
                            <div class="task-title">@ic.Issue.Name</div>
                            <div class="task-description"><span style="font-weight: bold">Описание: </span>@ic.Issue.Description</div>

                            @if (ic.Issue.DeadlineDate.Date <= DateTime.Now.Date && ic.Issue.Status != IssueStatus.Completed)
                            {
                                <div><span style="font-weight: bold">Срок: </span><span style="color: #a82f2f; font-weight: bold;">@ic.Issue.DeadlineDate.ToString("d")</span></div>
                            }
                            else
                            {
                                <div><span style="font-weight: bold">Срок: </span>@ic.Issue.DeadlineDate.ToString("d")</div>
                            }
                            @if (ic.Issue.Status == IssueStatus.Completed && ic.Issue.EndDate.ToString("d") != "01.01.0001")
                            {
                                if (@ic.Issue.EndDate.Date <= ic.Issue.DeadlineDate.Date){
                                    <div><span style="font-weight: bold">Завершена: </span><span style="color: #1f5b0d; font-weight: bold;">@ic.Issue.EndDate.ToString("d")</span></div>
                                }
                                else
                                {
                                    <div><span style="font-weight: bold">Завершена: </span><span style="color: #a82f2f; font-weight: bold;">@ic.Issue.EndDate.ToString("d")</span></div>
                                }
                            }
                            <div><span style="font-weight: bold">Статус: </span>@Issue.StatusToString(ic.Issue.Status)</div>
                            <div><span style="font-weight: bold">Приоритет: </span>@Issue.PriorityToString(ic.Issue.Priority)</div>
                            <div class ="task-description"><span style="font-weight: bold">Ответственный: </span>@ic.Issue.Performer.Email</div>
                            <div class="task-description"><span style="font-weight: bold">Создатель: </span>@ic.Issue.Creator.Email</div>
                        </div>

                    </a>
                }
            </div>
        }
    </div>
</div>

<!--------------------------------------------------------------->
<form asp-action="EditBoard" asp-controller="Boards" id="edit-board" class="modal">
    <input type="hidden" value="@ViewBag.BoardID" name="boardID" />
    <label class="input-form__label">
        <span class="input-placeholder">название</span>
        <input class="form__input input-name" name="Name" autocomplete="off" required value="@ViewBag.BoardName">
    </label>
    <button class="add-board-button">Сохранить</button>
    <a href="#" rel="modal:close"></a>
</form>

<form asp-action="CreateTask" asp-controller="Boards" id="add-task" class="modal createTask" method="post">
    <input type="hidden" value="@ViewBag.BoardID" name="boardID"/>
    <label class="input-form__label">
        <span class="input-placeholder">название</span>
        <input class="form__input input-task" name="Name" autocomplete="off" required>
    </label>
    <label class="input-form__label">
        <span class="input-placeholder">описание</span>
        <input class="form__input input-task-description" name="Description" autocomplete="off">
    </label>

    <label class="input-form__label">
        <span class="input-placeholder">срок</span>
        <input class="form__input input-date" type="date" name="DeadlineDate" required value="@DateTime.Now.ToString("yyyy-MM-dd")">
    </label>
    <label class="input-form__label">
        <span class="input-placeholder">статус</span>
        <select class="form__input input-select" name="Status" required>
            <option value="0" selected>Сделать</option>
            <option value="1">В процессе</option>
            <option value="2">Проверяется</option>
        </select>
    </label>
    <label class="input-form__label">
        <span class="input-placeholder">приоритет</span>
        <select class="form__input input-select" name="Priority" required>
            <option value="0" selected>низкий</option>
            <option value="1">средний</option>  
            <option value="2">высокий</option>
        </select>
    </label>
    <label class="input-form__label">
        <span class="input-placeholder">ответственный</span>
        <select class="form__input input-select" name="PerformerID" required>
            @foreach (SelectListItem option in ViewBag.Responsibilities)
            {
                <option value="@option.Value">@option.Text</option>
            }
        </select>
    </label>

    <button class="add-board-button">Добавить</button>
    <a href="#" rel="modal:close"></a>
</form>


@* <form asp-action="DeleteColumn" asp-controller="Boards" id="delete-column" class="modal delete" method="post">
    <input type="hidden" value="@ViewBag.BoardID" name="boardID" />
    <input type="hidden" id="columnID" name="columnID"/>
    <p>Подтвердите удаление колонки.</p>
    <button class="add-board-button">Подтвердить</button>
    <a href="#" rel="modal:close"></a>
</form> *@


<form asp-action="DeleteBoard" asp-controller="Boards" id="delete-board" class="modal delete" method="post">
    <input type="hidden" value="@ViewBag.BoardID" name="boardID"/>
    <p>Подтвердите удаление доски.</p>
    <button class="add-board-button">Подтвердить</button>
    <a href="#" rel="modal:close"></a>
</form>

<form asp-action="GenerateLink" asp-controller="Boards" id="generate-link" class="modal generateLink" method="get">
    <input type="hidden" value="@ViewBag.BoardID" name="boardID"/>
    <p>Генерация одноразовой ссылки для подключения к доске</p>
    <button onclick="navigator.clipboard.writeText('https://localhost:7203/Boards/JoinBoard/@ViewBag.BoardID'); return false;" class="add-board-button">Скопировать ссылку</button>

    @* https://localhost:7203/Boards/JoinBoard/@ViewBag.BoardID *@
    <a href="#" rel="modal:close"></a>
</form>

<div id="edit-task" class="modal editTask">
    @foreach (Issue task in ViewBag.BoardTasks)
    {
        <div ID="ISSUE@(@task.ID)" class="hidden issueform">
            <form asp-action="EditTask" asp-controller="Boards" method="post">
            <input type="hidden" value="@ViewBag.BoardID" name="boardID" />
            <input type="hidden" value="@task.ID" name="taskID" id="taskID"/>
            <label class="input-form__label">
                <span class="input-placeholder">название</span>
                <input class="form__input input-task" name="Name" autocomplete="off" required value="@task.Name">
            </label>
            <label class="input-form__label">
                <span class="input-placeholder">описание</span>
                    <input class="form__input input-task-description" name="Description" autocomplete="off" value="@task.Description">
            </label>

            <label class="input-form__label">
                <span class="input-placeholder">срок</span>
                <input class="form__input input-date" type="date" name="DeadlineDate" required value="@task.DeadlineDate.ToString("yyyy-MM-dd")">
            </label>
            <label class="input-form__label">
                <span class="input-placeholder">статус</span>
                <select class="form__input input-select" name="Status" required>
                    <!option value="0" @((task.Status == IssueStatus.ToDo) ? "selected" : "")>Сделать</!option>
                    <!option value="1" @((task.Status == IssueStatus.InProcess) ? "selected" : "")>В процессе</!option>
                    <!option value="2" @((task.Status == IssueStatus.Review) ? "selected" : "")>Проверяется</!option>
                    <!option value="3" @((task.Status == IssueStatus.Completed) ? "selected" : "")>Выполнена</!option>
                </select>
            </label>
            <label class="input-form__label">
                <span class="input-placeholder">приоритет</span>
                <select class="form__input input-select" name="Priority" required>
                    <!option value="0" @((task.Priority == Priority.Low) ? "selected" : "")>низкий</!option>
                    <!option value="1" @((task.Priority == Priority.Middle) ? "selected" : "")>средний</!option>
                    <!option value="2" @((task.Priority == Priority.High) ? "selected" : "")>высокий</!option>
                </select>
            </label>
            <label class="input-form__label">
                <span class="input-placeholder">ответственный</span>
                <select class="form__input input-select" name="PerformerID" required>
                    @foreach (SelectListItem option in ViewBag.Responsibilities)
                    {
                            <!option value="@option.Value" @((task.Performer.Email == option.Text) ? "selected" : "")>@option.Text</!option>
                    }
                </select>
            </label>

            <button class="add-board-button">Сохранить</button>
            </form>

            <form asp-action="DeleteTask" asp-controller="Boards" method="post" >
                <input type="hidden" value="@ViewBag.BoardID" name="boardID" />
                <input type="hidden" value="@task.ID" name="taskID" />
                <button class="add-board-button">Удалить</button>
            </form>
        </div>
        }
    <a href="#" rel="modal:close"></a>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const buttons = document.querySelectorAll('.edit-task-link');
        buttons.forEach(button => {
            button.addEventListener('click', function () {
                const taskID = this.getAttribute('data-task-id');
                document.getElementById('taskID').value = taskID;

                document.querySelectorAll('.issueform').forEach(element => {
                    if (!element.classList.contains('hidden')) {
                        element.classList.add('hidden');
                    }
                });
                document.getElementById('ISSUE'+taskID).classList.remove("hidden");
            });
        });
    });
</script>